//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dywham.Breeze.Apps.ChannelProcessingSystem.Engine.Tests.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Dywham.Breeze.Apps.ChannelProcessingSystem.Engine.Tests.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;Functions&quot;:[{&quot;Name&quot;:&quot;A&quot;,&quot;Expression&quot;:&quot;X + Y&quot;,&quot;Description&quot;:null,&quot;Metrics&quot;:&quot; { \&quot;Mean\&quot;: \&quot;f\&quot; }&quot;,&quot;Id&quot;:&quot;00000000-0000-0000-0000-000000000000&quot;,&quot;Version&quot;:0}],&quot;Parameters&quot;:{},&quot;Channels&quot;:{&quot;X&quot;:[2.0,4.0,8.0,12.0],&quot;Y&quot;:[4.0,8.0,8.0,8.0]},&quot;CalculatedMetrics&quot;:{&quot;f&quot;:13.5}}.
        /// </summary>
        internal static string CalculatorProviderTests_1 {
            get {
                return ResourceManager.GetString("CalculatorProviderTests_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;Functions&quot;:[{&quot;Name&quot;:&quot;A&quot;,&quot;Expression&quot;:&quot;X + Y&quot;,&quot;Description&quot;:null,&quot;Metrics&quot;:&quot; { \&quot;Mean\&quot;: \&quot;f\&quot; }&quot;,&quot;Id&quot;:&quot;00000000-0000-0000-0000-000000000000&quot;,&quot;Version&quot;:0},{&quot;Name&quot;:&quot;B&quot;,&quot;Expression&quot;:&quot;X + Z&quot;,&quot;Description&quot;:null,&quot;Metrics&quot;:null,&quot;Id&quot;:&quot;00000000-0000-0000-0000-000000000000&quot;,&quot;Version&quot;:0}],&quot;Parameters&quot;:{},&quot;Channels&quot;:{&quot;X&quot;:[2.0,4.0,8.0,12.0],&quot;Y&quot;:[4.0,8.0,8.0,8.0]},&quot;CalculatedMetrics&quot;:{&quot;f&quot;:13.5},&quot;InvalidFunctions&quot;:[&quot;B&quot;]}.
        /// </summary>
        internal static string CalculatorProviderTests_2 {
            get {
                return ResourceManager.GetString("CalculatorProviderTests_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;Functions&quot;:[{&quot;Name&quot;:&quot;A&quot;,&quot;Expression&quot;:&quot;X + Y&quot;,&quot;Description&quot;:null,&quot;Metrics&quot;:null,&quot;Id&quot;:&quot;00000000-0000-0000-0000-000000000000&quot;,&quot;Version&quot;:0}],&quot;Parameters&quot;:null,&quot;Channels&quot;:{&quot;X&quot;:[2.0,4.0,8.0,12.0],&quot;Y&quot;:[4.0,8.0,8.0,8.0]},&quot;ComputedChannels&quot;:{&quot;A&quot;:[6.0,12.0,16.0,20.0]},&quot;CalculatedMetrics&quot;:null,&quot;InvalidFunctions&quot;:null}.
        /// </summary>
        internal static string CalculatorProviderTests_3 {
            get {
                return ResourceManager.GetString("CalculatorProviderTests_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;Functions&quot;:{&quot;A&quot;:&quot;B+X&quot;,&quot;B&quot;:&quot;A+X&quot;},&quot;InvalidFunctions&quot;:[&quot;A&quot;,&quot;B&quot;],&quot;TranslatedFunctions&quot;:null}.
        /// </summary>
        internal static string ExpressionTranslationProviderTests_1 {
            get {
                return ResourceManager.GetString("ExpressionTranslationProviderTests_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;Functions&quot;:{&quot;A&quot;:&quot;B+X&quot;,&quot;B&quot;:&quot;A+X&quot;,&quot;C&quot;:&quot;c+X&quot;},&quot;InvalidFunctions&quot;:[&quot;A&quot;,&quot;B&quot;],&quot;TranslatedFunctions&quot;:[&quot;C&quot;]}.
        /// </summary>
        internal static string ExpressionTranslationProviderTests_2 {
            get {
                return ResourceManager.GetString("ExpressionTranslationProviderTests_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;Functions&quot;:{&quot;A&quot;:&quot;B+X&quot;,&quot;B&quot;:&quot;C+X&quot;,&quot;C&quot;:&quot;X+c&quot;},&quot;InvalidFunctions&quot;:null,&quot;TranslatedFunctions&quot;:[&quot;A&quot;,&quot;B&quot;,&quot;C&quot;]}.
        /// </summary>
        internal static string ExpressionTranslationProviderTests_3 {
            get {
                return ResourceManager.GetString("ExpressionTranslationProviderTests_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;Functions&quot;:{&quot;A&quot;:&quot;B++X&quot;,&quot;B&quot;:&quot;mX+c&quot;},&quot;InvalidFunctions&quot;:[&quot;A&quot;,&quot;B&quot;],&quot;TranslatedFunctions&quot;:null}.
        /// </summary>
        internal static string ExpressionTranslationProviderTests_4 {
            get {
                return ResourceManager.GetString("ExpressionTranslationProviderTests_4", resourceCulture);
            }
        }
    }
}
